version: '2.0'
services:
  mtprotoproxy:
    image: yuanhu66/mtprotoproxy
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./config.py:/app/config.py:ro
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"
    mem_limit: 2048m
